name: Test

on:
  pull_request:
  push:

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v4
        with:
          python-version: "3.12"
      - name: Install poetry
        run: python -m pip install poetry
      - name: Install requirements
        run: poetry install
      - run: poetry run pre-commit run --all-files

  test:
    runs-on: ubuntu-latest
    continue-on-error: true
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.11", "3.12"]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install poetry
        run: python -m pip install poetry
      - name: Install requirements
        run: poetry install
      - run: poetry run pytest
